#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/sbin/cake-autorate-reborn

start_instance() {
    local cfg="$1"
    local enabled

    config_get_bool enabled "$cfg" enabled 0
    [ "$enabled" -eq 1 ] || return 0

    procd_open_instance "$cfg"
    procd_set_param command "$PROG" "$cfg"
    procd_set_param respawn 3600 5 0
    procd_set_param stderr 1
    procd_close_instance
}

start_service() {
    config_load cake_autorate_reborn
    config_foreach start_instance cake_autorate_reborn
}

stop_service() {
    return 0
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger cake_autorate_reborn
}
